---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
- name: instance
  image: docker.io/pycontribs/ubuntu:latest
  pre_build_image: true
  command: ""
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:ro
  privileged: true
  tmpfs:
  - /tmp
  - /run
  - /run/lock
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        ansible_user: root
verifier:
  name: ansible
