---
# Docker installation tasks for traefik-ha role

- name: Install required packages for Docker
  ansible.builtin.package:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - gnupg
    state: present
  when: ansible_os_family == 'Debian'

- name: Add Docker GPG key (Debian/Ubuntu)
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present
  when: ansible_os_family == 'Debian'

- name: Add Docker repository (Debian/Ubuntu)
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present
    filename: docker
  when: ansible_os_family == 'Debian'

- name: Install Docker packages (Debian/Ubuntu)
  ansible.builtin.package:
    name:
    - docker
    state: present
  when: ansible_os_family == 'Debian'

- name: Install required packages (RHEL/CentOS)
  ansible.builtin.package:
    name:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    state: present
  when: ansible_os_family == 'RedHat'

- name: Add Docker repository (RHEL/CentOS)
  ansible.builtin.command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
  when: ansible_os_family == 'RedHat'

- name: Install Docker packages (RHEL/CentOS)
  ansible.builtin.package:
    name:
    - docker
    - docker-compose-plugin
    state: present
  when: ansible_os_family == 'RedHat'

- name: Create Docker service directory
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: '0755'

- name: Start and enable Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Install python3-docker package for Ansible Docker modules
  ansible.builtin.package:
    name: python3-docker
    state: present
