---
# Handlers for traefik-ha role

- name: Restart keepalived
  ansible.builtin.service:
    name: keepalived
    state: restarted

- name: Restart traefik
  community.docker.docker_compose_v2:
    project_src: "{{ traefik_config_dir }}"
    files:
      - docker-compose.yml
    state: restarted
